name: User Story
description: Create a new user story for sprint planning
title: "[ST-###] "
labels: ["story"]
body:
  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: Unique identifier (e.g., ST-001)
      placeholder: ST-###
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: "Format: As a [role], I want to [action], so that [benefit]"
      placeholder: |
        As a warehouse manager
        I want to record stock receipts with unit cost
        So that new inventory is tracked with accurate valuation
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List all AC-### items this story must satisfy
      placeholder: |
        - AC-002-1: Receipt creates new StockLot with qty/cost/timestamp
        - AC-002-2: ProductStock.qtyOnHand increments correctly
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale & Context
      description: Why is this story important? Any technical constraints?
      placeholder: Supports FIFO costing required for financial reporting
    validations:
      required: false

  - type: dropdown
    id: sprint
    attributes:
      label: Sprint
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
        - Backlog
    validations:
      required: true
