# BMAD Workflow Checklist
# Track sprint progress through Build-Measure-Analyze-Deploy stages

name: BMAD Sprint Workflow

# This is a manual checklist, not automated CI
# Update this file as you progress through stages

stages:
  plan:
    - [ ] PRD.md reviewed and approved
    - [ ] ARCH.md reviewed by tech leads
    - [ ] QA.md acceptance criteria defined
    - [ ] GitHub issues created for all stories (ST-###)
    - [ ] Database schema changes identified

  build:
    - [ ] Database migrations created and tested locally
    - [ ] API routes implemented with Zod validation
    - [ ] OpenAPI schemas defined and types generated
    - [ ] Service layer logic with business rules
    - [ ] Permission middleware applied to routes
    - [ ] Frontend API clients created
    - [ ] UI components implemented
    - [ ] Unit tests written (target 80%+ coverage)

  measure:
    - [ ] API tests pass (see Makefile: bmad-test-api)
    - [ ] Frontend builds without errors (bmad-test-web)
    - [ ] Manual testing completed for each AC-###
    - [ ] Performance checks (P95 latency < 500ms)
    - [ ] Audit logs verified for stock operations
    - [ ] RBAC permission checks validated

  analyze:
    - [ ] Code review completed (PR approved)
    - [ ] Test coverage report reviewed
    - [ ] Security scan passed (no critical vulnerabilities)
    - [ ] Database migration dry-run in staging
    - [ ] Rollback plan documented

  deploy:
    - [ ] Merged to main branch
    - [ ] Migrations applied to staging
    - [ ] Smoke tests passed in staging
    - [ ] Production deployment completed
    - [ ] Post-deployment verification (health checks)
    - [ ] Metrics dashboard updated

# Notes:
# - Check off items as you complete them
# - Link to PR numbers and test evidence in commit messages
# - Update QA.md if acceptance criteria change during build
